name: iCub-Narrow-Passage-LAGS
K: 5.0
M: 2.0
Priors: [0.01737733644859813, 0.039281542056074766, 0.019421728971962617, 0.026869158878504672,
  0.040011682242990655]
Mu: [1.0275146303757137, 0.28328815479401165, 1.7250337820134236, 1.0809664554136151,
  2.020856412689238, 3.3880098106902716, 3.24884656151145, 3.7902049562634157, 1.6844448369219178,
  2.4377341072579446]
Sigma: [0.14105067871927526, 0.04214313864500182, 0.04214313864500181, 0.057154628532989096,
  0.025733786452352685, -0.0100876424902078, -0.010087642490207799, 0.09581993973520986,
  0.07683370575066785, 0.023368167372753337, 0.02336816737275333, 0.03158540748530737,
  0.11041409659516012, 0.028117908799863818, 0.028117908799863825, 0.039902997166682996,
  0.04191051774402293, -0.0038147506571252626, -0.0038147506571252618, 0.1670612181751526]
A_g: [-0.0011142813970005392, 0.07602484701817551, -0.08237336619902925, -0.08916766610659356,
  -0.0570151450857924, -0.048831527001719964, 0.03430160351471288, -0.0019422391834868894,
  -0.10043497221013797, -0.02751335809185365, -0.01348153846823694, -0.09909074436285403,
  -0.3738816028916783, -0.03906106237754095, -0.1306997639022531, -0.2609420873329629,
  -0.04426488114356111, -0.015628187355468722, 0.05395432351120138, -0.06834853964260364]
att_g: [3.595471462860727, 3.913926366397385]
A_l: [0.0, 0.0, 0.0, 0.0, -1.0465993003949663, -0.14491718957518768, -0.14491718957518768,
  -0.06362018581848024, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.0, -1.2405635559206398,
  0.007733945991917621, 0.007733945991917621, -0.21120842644450005]
A_d: [0.0, 0.0, 0.0, 0.0, 0.5337593683707301, 0.0, 0.0, 0.5337593683707301, 0.0, 0.0,
  0.0, 0.0, 0.0, 0.0, 0.0, 0.0, 0.10557516078805287, 0.0, 0.0, 0.10557516078805439]
att_l: [1.7759169721555705, 0.6059628126437482, 1.6235936120082917, 1.7836825374192344,
  2.5782461832820407, 3.7414452979273696, 3.595471462860727, 3.913926366397385, 1.690642858440763,
  3.2627108248259247]
w_l: [-0.9182850819384594, -0.3959198255824997, 0.1428734788804798, -0.9897409605712947,
  -0.8445299554436023, -0.5355083139956158, -0.9418048896504986, -0.3361600062922601,
  -0.007512753356185691, -0.9999717788702884]
b_l: [20.0, 20.0, 20.0, 20.0, 20.0]
scale: 5.0
b_g: 10.0
gpr_path: /home/nbfigueroa/Dropbox/PhD_papers/LAGS-paper/new-code/lagsDS-opt//models/iCub-Narrow-Passage-LAGS/GPR_model.txt
x0_all: [0.4171277040516006, 0.1108361719990621, 0.3243519772494339, 0.06538538211131481,
  0.49475383414248775, 0.04381718818202839]
dt: 0.0062161082078081775
