name: KUKA-KhameshShape-LAGS
K: 4.0
M: 2.0
Priors: [0.0718562874251497, 0.08982035928143713, 0.08383233532934131, 0.08802395209580838]
Mu: [-0.24536275856571985, -0.24026526654140962, -0.012199255039266088, -0.04616039366442031,
  -0.3351648436782644, -0.21848458038880772, -0.11549741544114563, -0.14740225245577088]
Sigma: [0.001371664259906026, 6.670280720589366E-4, 6.670280720589365E-4, 0.0013996785730277014,
  7.412901519756618E-4, 3.511727052210066E-4, 3.5117270522100656E-4, 0.0016592090657998073,
  5.494944981798367E-4, -2.2332976888602638E-4, -2.2332976888602638E-4, 0.0013445921046071133,
  0.0021410800648990437, 2.937749638066652E-4, 2.937749638066652E-4, 8.344437013132114E-4]
A_g: [-0.7757286114378897, 0.19398364893656805, -0.41011253327056774, -1.327945512175443,
  -2.21999971097542, 15.299232081913651, -1.3601703976298536, -9.206043325768816,
  -0.16180479287411267, 0.6865335616522193, -0.1723382634328523, 0.09529966404798193,
  -1.3803869227841532, -0.07317556375882191, -0.9347607249483192, -0.6419237171840972]
att_g: [0.0, 0.0]
A_l: [-12.181803041222308, 13.97354091726632, 13.97354091726632, -18.70513351670778,
  -34.512609103304456, 9.570787482901226, 9.570787482901226, -3.9953894378837393,
  -1.740244173525824, -0.7841107366378368, -0.7841107366378368, -0.5494016528411767,
  -6.9268050347696075, 14.856111915411047, 14.856111915411047, -43.17528735411946]
A_d: [0.54715565204482, 0.0, 0.0, 0.54715565204482, 0.6210967506643257, 0.0, 0.0,
  0.6210967506643257, 0.0801320327432685, 0.0, 0.0, 0.0801320327432685, 0.8080982643369201,
  0.0, 0.0, 0.8080982643369201]
att_l: [-0.14332857578291958, -0.15820401028118675, 0.0, 0.0, -0.29971961186024454,
  -0.28633642299043377, -0.020427401270206744, -0.11335200612944263]
w_l: [-0.783360421035693, -0.6215677362563005, -0.276455309066547, -0.9610267749074007,
  -0.44454502414911934, 0.8957565079329645, -0.9416444158026793, -0.336609260400885]
b_l: [100.0, 100.0, 100.0, 100.0]
scale: 10.0
b_g: 200.0
gpr_path: /home/nbfigueroa/Dropbox/PhD_papers/LAGS-paper/new-code/lagsDS-opt/models/KUKA-KhameshShape-LAGS/GPR_model.txt
x0_all: [-0.33222794370194453, -0.17894697585583705, -0.3555310542101809, -0.18624608228606482,
  -0.3183718232442135, -0.1670331411244458, -0.3636920539606869, -0.19048282593428947,
  -0.3640510948905108, -0.1856367676313145]
dt: 0.0035720332752188074
