K: 1.0
dim: 6.0
Priors: [1.0]
Mu: [0, 0, 0, 0, 0, 0]
Sigma: [1,0,0,-1,0,0,
        0,1,0,0,-1,0,
        0,0,1,0,0,-1,
       -1,0,0,1,0,0,
        0,-1,0,0,1,0,
        0,0,-1,0,0,1]

attractor: [0, 0, 0, 0.0, 0.0, 0.0]
ee_tool_offset: [0, 0, 0.2]